### ISSUE TITLE
about the original source code

### ISSUE THREAD

**Issue by scnb** [irving-muller/fast-dbrd-modified#1]
hi, I find that the original source code link you mentioned in the Readme.md is not available, so I wonder if you still have a copy of the source code, and can you send me a copy, thanks.

**Comment by irving-muller** [comment]
Hello,

It seems that the URL is not broken. I could download the source code using that link. Could you please try again?

**Comment by scnb** [comment]
hi, it turns out that the VPN software didn't work well on my PC, but it
did work well on my phone, so I just downloaded the source code. Thanks
anyway and sorry to bother you. Have a good day

irving-muller <notifications@github.com> 于 2021年2月25日周四 05:56写道：
