### ISSUE TITLE
Regarding the final config chosen in the paper

### ISSUE THREAD

**Issue by happygirlzt** [irving-muller/fast-dbrd-modified#2]
Hey, @irving-muller! :) It's me again. ;)

I wonder whether you selected `full-textual-no-version.cfg` as the final configuration for REP. Which means, the results reported in the paper are with` full-textual-no-version.cfg`.
(I experimented on REP with ` full-textual-full-categorial.cfg` and achieved quite high recall rates@k.)

Many thanks for your help like usual. Have a nice week!

**Comment by irving-muller** [comment]
Hello @happygirlzt,

Sorry for the delay.

REP's authors manually recovered  the chronological order of all the versions of one repository (OpenOffice). For the other ones, they ignored the report version information  since it is not straightforward to compare versions in the repositories. Versions labels may not be numbers and they may not following the same pattern. Moreover, the release date of a version might be difficult to be retrieved. Even though version is a useful feature for the methods, due to these difficulties, we decided to not employ the version in all repositories.

**Comment by happygirlzt** [comment]
Hi @irving-muller :) not a delay at all.

I see, so you use the `full-textual-no-version.cfg` for REP and `no-query-no-categorial.cfg` for BM25_ext, right?

Thank you once more. :)
Have a nice Friday and weekend ahead!

**Comment by irving-muller** [comment]
Hi @happygirlzt ,

It is correct for REP. Regarding  BM25_ext, I used `with-query-no-categorial.cfg` since this technique uses the query information. For the tradicional BM25, the configuration file is `no-query-no-categorial.cfg`.

Let me know if you have any other question.

Have a nice Friday!! :)

**Comment by happygirlzt** [comment]
Hi @irving-muller ,

I see :) Many thanks for the details!

Have a nice weekend!

**Comment by happygirlzt** [comment]
Heyyy @irving-muller ! Sorry, I'm still bothering you.. ): Hope this is the last time.
I have three things want to confirm regarding REP.

1. Do you directly take the recall rate @k from the output of this script as the result? Have you done any other calculations? As I found REP recall rate@k is quite good, if I directly use the output. 
<img width="336" alt="Screenshot 2021-08-18 at 19 27 49" src="https://user-images.githubusercontent.com/15061984/129891740-a1bdab37-987a-43c7-a25a-c42845a0f48e.png"> In this case, I just report the average recall rate in the end of the generated file`dbrd_ranknet_rep_xxxx`

2. You mentioned you run REP on Netbeans dataset 10 times, did you run 10 iterations? Just like the following 

```
./build/bin/fast-dbrd -i 10 -n rep_eclipse_no_version -r ./ranknet-configs/full-textual-no-version.cfg --ts /HOME_DIRECTORY/dataset/eclipse/timestamp_file.txt --time-constraint 365 --training-duplicates 922 --recommend /HOME_DIRECTORY/dataset/eclipse/dbrd_test.txt
```

which mean `-i 10` indicates you run it 10 times.

3. For the `training-duplicates` that this is the duplicate bug number in the `training_BTS.txt` right?

Sorry... I have been bothering you so many times.. I sincerely feel really grateful about it.
Have a nice week! :)

**Comment by irving-muller** [comment]
Hello @happygirlzt. Sorry for the delay. 

> Do you directly take the recall rate @k from the output of this script as the result? Have you done any other calculations? As I found REP recall rate@k is quite good, if I directly use the output.

Yes, RR@k and MAP values reported on the paper were calculated using this script.

> You mentioned you run REP on Netbeans dataset 10 times, did you run 10 iterations? Just like the following

No, I do not use the argument `-i`. I **manually** ran  5 or 10 times REP depending of the dataset. We can modify argument `-n` value for that.

> For the training-duplicates that this is the duplicate bug number in the training_BTS.txt right?

This is only correct if you want to evaluate REP on the validation . For the test set, we have to **use the sum of the number of duplicates in the **training** and **validation****. For instance, the correct command to evaluate REP on the test set using a window of 365 days is:  

`./build/bin/fast-dbrd -n rep_eclipse_365_test_1 -r ranknet-configs/full-textual-no-version.cfg --ts /HOME_DIRECTORY/dataset/eclipse/timestamp_file.txt --time-constraint 365 --training-duplicates 28927 --recommend /HOME_DIRECTORY/dataset/eclipse/dbrd_test.txt`
 
Below, I list the parameter `training-duplicates` values for each dataset:

- Eclipse: 28927
- Mozilla: 166213
- OpenOffice: 14284
- Netbeans: 17514

Please let me know if you have any further question.

Have a nice week! :)

**Comment by happygirlzt** [comment]
Hey @irving-muller , many thanks for your reply! :)
> Yes, RR@k and MAP values reported on the paper were calculated using this script.

Ah, so it means you did **other further** calculation? Didn't you **directly** use the results returned by running this command?

> No, I do not use the argument -i. I manually ran 5 or 10 times REP depending of the dataset. We can modify argument -n value for that.

If I'm not wrong, `-n` indicates the filename of the generated results. So do you mean, we can run the same datasets with one iteration many times by changing the filenames :)
> This is only correct if you want to evaluate REP on the validation . For the test set, we have to use the sum of the number of duplicates in the training and validation. For instance, the correct command to evaluate REP on the test set using a window of 365 days is:

I guess what I mean is the same as your. As based on your naming tradition, `training_BTS.txt` includes both `training` and `validation`. Only `training_split_BTS.txt` excludes `validation`.

Many thanks for your patience and time again!
Have a great week! Love ❤️

**Comment by irving-muller** [comment]
Hey @happygirlzt 

> Ah, so it means you did other further calculation? Didn't you directly use the results returned by running this command?

No, you were right. I directly use the results computer by `fast-dbrd`. Sorry that my answer was not clear.

`If I'm not wrong, -n indicates the filename of the generated results. So do you mean, we can run the same datasets with one iteration many times by changing the filenames :)`

Yes :)

> I guess what I mean is the same as your. As based on your naming tradition, training_BTS.txt includes both training and validation. Only training_split_BTS.txt excludes validation.
 
Yes, that is correct :+1:   :)

Can you achieve similar results to the ones reported in the paper?

**Comment by happygirlzt** [comment]
Hey @irving-muller !
Many thanks for your reply :)
Previously, I use different iterations, such as `-i 5`, my replicated result of REP was similar but slightly better than the reported ones in the paper. But I think it is normal. (as there is some randomness)
Thank you very much again! :)
